# Source: jxboot-helmfile-resources/templates/environments.yaml
apiVersion: jenkins.io/v1
kind: Environment
metadata:
  labels:
    env: "dev"
    team: jx
    gitops.jenkins-x.io/pipeline: 'environment'
  name: "dev"
  namespace: jx
spec:
  source:
    ref: "master"
    url: https://github.com/rawlingsj/test-terraform-gsm1.git
  kind: Development
  label: Development
  namespace: jx
  promotionStrategy: Never
  webHookEngine: "Lighthouse"
  teamSettings:
    appsRepository: http://chartmuseum.jenkins-x.io
    buildPackRef: "master"
    buildPackUrl: "https://github.com/jenkins-x/jxr-packs-kubernetes.git"
    defaultScheduler:
      apiVersion: jenkins.io/v1
      kind: Scheduler
      name: default
    dockerRegistryOrg: "jenkins-x-labs-bdd"
    envOrganisation: todo
    gitServer: https://github.com
    gitPublic: true
    helmTemplate: true
    kubeProvider: "gke"
    pipelineUsername: "jenkins-x-labs-bot"
    pipelineUserEmail: "jenkins-x@googlegroups.com"
    prowConfig: Scheduler
    importMode: YAML
    promotionEngine: Prow
    prowEngine: Tekton
    versionStreamUrl: "https://github.com/jenkins-x/jxr-versions.git"
    versionStreamRef: "master"
    useGitOps: true
    storageLocations:
    - bucketUrl: gs://logs-tc-rocks-43066b09b8cc
      classifier: logs
    - bucketUrl: gs://reports-tc-rocks-43066b09b8cc
      classifier: reports
