# Source: jxboot-helmfile-resources/templates/gh-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jx-pipeline-git-github-github
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: gcpSecretsManager
  projectId: jenkins-x-labs-bdd
  data:
  - name: password
    key: tc-rocks-jx-pipeline-user
    property: token
    version: latest
  - name: username
    key: tc-rocks-jx-pipeline-user
    property: username
    version: latest
  template:
    metadata:
      annotations:
        build.knative.dev/git-0: https://github.com
        jenkins.io/credentials-description: API Token for acccessing https://github.com
          Git service inside pipelines
        jenkins.io/name: github
        jenkins.io/url: https://github.com
      labels:
        jenkins.io/created-by: jx
        jenkins.io/credentials-type: usernamePassword
        jenkins.io/kind: git
        jenkins.io/service-kind: github
    type: Opaque
