# Source: jxboot-helmfile-resources/templates/maven-settings-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-maven-settings
  annotations:
    gitops.jenkins-x.io/kind: 'mandatory'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: gcpSecretsManager
  projectId: ROJECT_ID
  data:
  - name: settings.xml
    key: luster_name-jx-maven-settings
    property: settingsXml
    version: latest
  - name: settings-security.xml
    key: luster_name-jx-maven-settings
    property: securityXml
    version: latest
  template:
    type: Opaque
