# Source: jxboot-helmfile-resources/templates/maven-settings-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-maven-settings
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: gcpSecretsManager
  projectId: jenkins-x-labs-bdd
  data:
  - name: settings.xml
    key: tc-rocks-jx-maven-settings
    property: settingsXml
    version: latest
  - name: settings-security.xml
    key: tc-rocks-jx-maven-settings
    property: securityXml
    version: latest
  template:
    type: Opaque
