# Source: jxboot-helmfile-resources/templates/release-gpg-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-release-gpg
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: gcpSecretsManager
  projectId: jenkins-x-labs-bdd
  data:
  - name: pubring.gpg
    key: tc-rocks-jenkins-release-gpg
    version: latest
  - name: sec-jenkins.gpg
    key: tc-rocks-jenkins-release-gpg
    version: latest
  - name: secring.gpg
    key: tc-rocks-jenkins-release-gpg
    version: latest
  - name: trustdb.gpg
    key: tc-rocks-jenkins-release-gpg
    version: latest
  template:
    type: Opaque
