apiVersion: secret.jenkins-x.io/v1alpha1
kind: Schema
spec:
  objects:
  - name: jx-pipeline-git-github-github
    mandatory: true
  - name: jenkins-maven-settings
    mandatory: true
    properties:
    - name: settingsXml
      question: Maven settings XML contents
      help: This is the maven settings XML which is mounted for Java builds
      defaultValue: |-
        <settings>
            <!-- sets the local maven repository outside of the ~/.m2 folder for easier mounting of secrets and repo -->
            <localRepository>${user.home}/.mvnrepository</localRepository>
            <!-- lets disable the download progress indicator that fills up logs -->
            <interactiveMode>false</interactiveMode>
            <mirrors>
                <mirror>
                <id>nexus</id>
                <mirrorOf>external:*</mirrorOf>
                <url>http://nexus:8081/repository/maven-group/</url>
                </mirror>
            </mirrors>
            <servers>
                <server>
                <id>nexus</id>
                <username>admin</username>
                <password>admin123</password>
            </server>
            <server>
                <id>oss-sonatype-staging</id>
                <username></username>
                <password></password>
                </server>
            </servers>
            <profiles>
                <profile>
                    <id>nexus</id>
                    <properties>
                        <altDeploymentRepository>nexus::default::http://nexus/repository/maven-snapshots/</altDeploymentRepository>
                        <altReleaseDeploymentRepository>nexus::default::http://nexus/repository/maven-releases/</altReleaseDeploymentRepository>
                        <altSnapshotDeploymentRepository>nexus::default::http://nexus/repository/maven-snapshots/</altSnapshotDeploymentRepository>
                    </properties>
                </profile>
                <profile>
                    <id>release</id>
                    <properties>
                        <gpg.executable>gpg</gpg.executable>
                        <gpg.passphrase>mysecretpassphrase</gpg.passphrase>
                    </properties>
                </profile>
            </profiles>
            <activeProfiles>
                <!--make the profile active all the time -->
                <activeProfile>nexus</activeProfile>
            </activeProfiles>
        </settings>
    - name: securityXml
      question: Maven security XML contents
      help: This is the maven security XML which is mounted for Java builds
      defaultValue: |-
        <<settingsSecurity/>
