# Source: nexus/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: nexus
  annotations:
    gitops.jenkins-x.io/kind: 'mandatory'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: gcpSecretsManager
  projectId: ROJECT_ID
  data:
  - name: password
    key: luster_name-jx-admin-user
    property: password
    version: latest
  template:
    metadata:
      labels:
        app: nexus-nexus
        chart: "nexus-0.1.35"
        release: "nexus"
        heritage: "Helm"
    type: Opaque
