# Source: tekton/templates/250-git-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: knative-git-user-pass
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: gcpSecretsManager
  projectId: ROJECT_ID
  data:
  - name: password
    key: luster_name-jx-pipeline-user
    property: token
    version: latest
  - name: username
    key: luster_name-jx-pipeline-user
    property: username
    version: latest
  template:
    metadata:
      annotations:
        tekton.dev/git-0: "https://github.com"
    type: kubernetes.io/basic-auth
