# Source: tekton/templates/250-docker-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: knative-docker-user-pass
  annotations:
    gitops.jenkins-x.io/kind: 'mandatory'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: gcpSecretsManager
  projectId: ROJECT_ID
  data:
  - name: password
    key: luster_name-jx-docker
    property: password
    version: latest
  - name: username
    key: luster_name-jx-docker
    property: username
    version: latest
  template:
    metadata:
      annotations:
        tekton.dev/docker-0: ""
    type: kubernetes.io/basic-auth
