# Source: chartmuseum/templates/secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-x-chartmuseum
  annotations:
    gitops.jenkins-x.io/kind: 'mandatory'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: gcpSecretsManager
  projectId: ROJECT_ID
  data:
  - name: BASIC_AUTH_PASS
    key: luster_name-jx-admin-user
    property: password
    version: latest
  - name: BASIC_AUTH_USER
    key: luster_name-jx-admin-user
    property: username
    version: latest
  template:
    metadata:
      annotations:
        jenkins.io/credentials-keybinding-password: BASIC_AUTH_PASS
        jenkins.io/credentials-keybinding-username: BASIC_AUTH_USER
      labels:
        jenkins.io/credentials-type: usernamePassword
        app: chartmuseum
        chart: chartmuseum-1.1.7
        heritage: "Helm"
        release: "chartmuseum"
    type: Opaque
