# Source: lighthouse/templates/hmacsecret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: lighthouse-hmac-token
  annotations:
    gitops.jenkins-x.io/kind: 'mandatory'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'environment'
spec:
  backendType: gcpSecretsManager
  projectId: ROJECT_ID
  data:
  - name: hmac
    key: luster_name-lighthouse-hmac
    property: token
    version: latest
  template:
    metadata:
      labels:
        app: lighthouse-lighthouse
        chart: "lighthouse-0.0.683"
        release: "lighthouse"
        heritage: "Helm"
    type: Opaque
